### ISSUE TITLE
Run examples in CI

### ISSUE THREAD

**Issue by alice-i-cecile** [Leafwing-Studios/template-repo#26]

**Comment by alice-i-cecile** [comment]
Initial attempts were not satisfactory. #29 is particularly challenging, but we also need an example-agnostic way to kill examples that are taking too long.

Draft workflow:

```yaml

  run-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Install Bevy dependencies
        run: |
          sudo apt-get update;
          DEBIAN_FRONTEND=noninteractive sudo apt-get install --no-install-recommends -yq \
            libasound2-dev libudev-dev;
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: runner.os−cargo−run−examples−{{ hashFiles('**/Cargo.toml') }}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
      - name: Build project
        run: |
          cargo +nightly build
      - name: Run examples
        run: |
          for example_name in example/*.rs; do
            cargo +nightly run −−example $(basename $example_name .rs)"
            sleep 3
          done
```
